// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSet":       schema_pkg_apis_cr_v1alpha1_ActionSet(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSetSpec":   schema_pkg_apis_cr_v1alpha1_ActionSetSpec(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSetStatus": schema_pkg_apis_cr_v1alpha1_ActionSetStatus(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.Blueprint":       schema_pkg_apis_cr_v1alpha1_Blueprint(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.BlueprintSpec":   schema_pkg_apis_cr_v1alpha1_BlueprintSpec(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.BlueprintStatus": schema_pkg_apis_cr_v1alpha1_BlueprintStatus(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.Profile":         schema_pkg_apis_cr_v1alpha1_Profile(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ProfileSpec":     schema_pkg_apis_cr_v1alpha1_ProfileSpec(ref),
		"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ProfileStatus":   schema_pkg_apis_cr_v1alpha1_ProfileStatus(ref),
	}
}

func schema_pkg_apis_cr_v1alpha1_ActionSet(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActionSet is the Schema for the actionsets API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSetSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSetStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSetSpec", "github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ActionSetStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cr_v1alpha1_ActionSetSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActionSetSpec defines the desired state of ActionSet",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cr_v1alpha1_ActionSetStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ActionSetStatus defines the observed state of ActionSet",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cr_v1alpha1_Blueprint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Blueprint is the Schema for the blueprints API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.BlueprintSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.BlueprintStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.BlueprintSpec", "github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.BlueprintStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cr_v1alpha1_BlueprintSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BlueprintSpec defines the desired state of Blueprint",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cr_v1alpha1_BlueprintStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BlueprintStatus defines the observed state of Blueprint",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cr_v1alpha1_Profile(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Profile is the Schema for the profiles API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ProfileSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ProfileStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ProfileSpec", "github.com/joshiomkarj/kanister/pkg/controllerv2/pkg/apis/cr/v1alpha1.ProfileStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cr_v1alpha1_ProfileSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProfileSpec defines the desired state of Profile",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cr_v1alpha1_ProfileStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ProfileStatus defines the observed state of Profile",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
